name: Bazel tests

on: [push, pull_request]

jobs:
  bazel-run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel
      - uses: actions/checkout@v2
      - name: Run Bazel tests
        run: bazel test ...:all --test_output=all --action_env=WGKEX_CONFIG_FILE=`pwd`/wgkex.yaml.example
      - name: Python coverage
        run: |
          cd "${GITHUB_WORKSPACE}/src"
          curl -L https://github.com/ulfjack/coveragepy/archive/lcov-support.tar.gz | tar xvz
          bazel coverage --javabase=@bazel_tools//tools/jdk:remote_jdk11 -t- --instrument_test_targets \
            --experimental_cc_coverage --test_output=errors --linkopt=--coverage --linkopt=-lc \
            --test_env=PYTHON_COVERAGE=${GITHUB_WORKSPACE}/src/coveragepy-lcov-support/__main__.py  \
            --define=config_file=test ...:all
          # Unfortunately, coverage does not produce the hit information. Running
          # the compiled tests explicitly seems to work though.
          find ./bazel-wgkex/ -size +1  -name "*coverage.dat" -exec ls -lh {} \;
