name: Bazel tests

on: [push, pull_request]

jobs:
  bazel-run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel
      - uses: actions/checkout@v2
      - name: Run Bazel tests
        run: bazel test ...:all --test_output=all --action_env=WGKEX_CONFIG_FILE=`pwd`/wgkex.yaml.example
